version: "3.7"
services:
  namenode:
    image: apache-hadoop:3.3.6
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - YARN_RESOURCEMANAGER_USER=root
      - YARN_NODEMANAGER_USER=root
    ports:
      - "9870:9870"
      - "8088:8088"
    command: >
      bash -lc "hdfs namenode & yarn resourcemanager"
    hostname: hdfs-namenode

  datanode:
    image: apache-hadoop:3.3.6
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - YARN_RESOURCEMANAGER_USER=root
      - YARN_NODEMANAGER_USER=root
    hostname: datanode
    depends_on:
      - namenode
    command: >
      bash -lc "hdfs datanode & yarn nodemanager"
    ports:
      - "9864"
    links:
      - namenode:hdfs-namenode

  secondarynamenode:
    image: apache-hadoop:3.3.6
    environment:
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - YARN_RESOURCEMANAGER_USER=root
      - YARN_NODEMANAGER_USER=root
    command: hdfs secondarynamenode
    ports:
      - "9868:9868"
    links:
      - namenode:hdfs-namenode
